### ISSUE TITLE
Create process to publish/update package on pypi

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/ckanext-datapackage-creator#1]
@gileno as talked, we must create an automated process to publish/update the package on [pypi](https://pypi.org/).

We did this in our [dpckan](https://github.com/transparencia-mg/dpckan) package using [this `Makefile`](https://github.com/transparencia-mg/dpckan/blob/dev/Makefile). We could do the same here.

The only problem/inconvenient will be updating the package version on `setup.py` file every new update on  [pypi](https://pypi.org/) because it doesn't allow to publish new code in already publish versions.

https://github.com/transparencia-mg/ckanext-datapackage-creator/blob/b7c1e718885dbdeb0c159c1c2b5534e2d551c45c/setup.py#L8-L11

To better document these new releases we could use our brand new [CHANGLOG.md](https://github.com/transparencia-mg/ckanext-datapackage-creator/blob/master/CHANGELOG.md) file.

To finish the task, please document all the steps used to realize the update in the `README.md` file. [Here is an example](https://github.com/transparencia-mg/dpckan/issues/6#issuecomment-851678297) that could be followed. 

TODO:
- [x] Create the `Makefile` and its necessary targets.
- [x] Publish package on PyPI (DTA account).
- [x] Include @gileno as "package maintainer"
- [x] Include @gabrielbdornas as package maintainer"
- [x] Document process on `README.md` file.

**Comment by gileno** [comment]
Ok, I will update

**Comment by gabrielbdornas** [comment]
@gileno what's your Pypi user?

**Comment by gileno** [comment]
Just **gileno**

**Comment by gabrielbdornas** [comment]
> Just **gileno**

@gileno you've been invited as package `maintainer` in [pypi](https://pypi.org/project/ckanext-datapackage-creator/)

![image](https://user-images.githubusercontent.com/49699290/205981551-c9311b79-8cf6-4f88-b03a-9e17c6c8aa5c.png)

**Comment by gileno** [comment]
@gabrielbdornas I accepted the invitation

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas I accepted the invitation

@gileno fine. The Package was published successfully. And all process was documented in [`README.md` file](https://github.com/transparencia-mg/ckanext-datapackage-creator).
