### ISSUE TITLE
Atualizar branch principal do projeto para `main`

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/ckanext-datapackage-creator#3]
@gileno do you mand if we change our branch `master` to `main`?

**Comment by gileno** [comment]
@gabrielbdornas I didn't realize it was master, I believe it was because the repository was created if the README.md and initial .gitignore
I will do

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas I didn't realize it was master, I believe it was because the repository was created if the README.md and initial .gitignore I will do

Great!

**Comment by gileno** [comment]
@gabrielbdornas I created the branch "main" but it is necessary to go to the repository settings to change it on github

**Comment by gabrielbdornas** [comment]
@gileno, modifiquei a branch principal do projeto para main:

![image](https://user-images.githubusercontent.com/49699290/208909192-ae4fbc0e-3770-4a84-9a4b-f2c2a377fe8e.png)

Solicito que realize o merge de tudo que está na master (ATUALIZAR COM EVENTUAIS COMMITS DA SUA MÁQUINA QUE POR VENTURA NÃO TENHA SIDO SINCRONIZADOS VIA PULL) na main via criação e aprovação de um PR.

Também habilitei esta funcionalidade no repositório:

![image](https://user-images.githubusercontent.com/49699290/208909557-d4a5b5ee-c786-4a8b-b644-1975326022d0.png)

Sendo assim, quando você aprovar o PR solicitado acima a branch `master` será excluída automanticamente. Após todo processo recomendo exclui-la de sua máquina também (`git branch -D master`) para evitar confusões.

Em caso de dúvidas estou à disposição.

**Comment by gileno** [comment]
@gabrielbdornas irei verificar

**Comment by gabrielbdornas** [comment]
Issue resolvido dia 26/12/2022 em reunião na parte da manhã com @gileno
