### ISSUE TITLE
Salvamento dos metadados

### ISSUE THREAD

**Issue by gileno** [transparencia-mg/ckanext-datapackage-creator#4]
@gabrielbdornas, @andreiadonca e @Andrelamor a extensão `ckanext validation` cria um novo modelo/tabela para salvamento das validações como visto em:

- [models.py](https://github.com/frictionlessdata/ckanext-validation/blob/master/ckanext/validation/model.py)

Seguindo a ideia deles seria melhor ter um modelo / tabela para salvar os metadados ao invés de salvar nos extras, vocês acham que o fato deles não salvarem nos extras faz com que seja melhor não salvarmos nos extras? Falta apenas essa decisão de tomada para subir as telas atualizadas salvando corretamente os dados

**Comment by gabrielbdornas** [comment]
@gileno , conforme informado por você a mudança para salvar em um novo modelo já foi realizada,  sendo assim fecharei o issue.
